// TODO: i18n
const ErrorEnum = {
    ERR_INVALID_PASSWORD: 'ERR_INVALID_PASSWORD',
    ERR_SET_USER_KEY: 'ERR_SET_USER_KEY',
    ERR_INVALID_USK: 'ERR_INVALID_USK',
    ERR_NOT_EXIST_USK: 'ERR_NOT_EXIST_USK',
    ERR_SET_USER_KEY_BY_SK: 'ERR_SET_USER_KEY_BY_SK',
    ERR_INVALID_ADDRESS: 'ERR_INVALID_ADDRESS',
    ERR_INVALID_PUB_KEY: 'ERR_INVALID_PUB_KEY',
    ERR_SET_EXADDR_AND_PRIVKEY: 'ERR_SET_EXADDR_AND_PRIVKEY',
    ERR_GET_EXADDR_AND_PRIVKEY: 'ERR_GET_EXADDR_AND_PRIVKEY',
    ERR_GET_PUB_KEY: 'ERR_GET_PUB_KEY',
    ERR_START_AZEROTH: 'ERR_START_AZEROTH',
    ERR_INVALID_MNEMONIC: 'ERR_INVALID_MNEMONIC',
    ERR_INVALID_PRIVATE_KEY: 'ERR_INVALID_PRIVATE_KEY',
    ERR_INVALID_DATA_TYPE: 'ERR_INVALID_DATA_TYPE'
};

Object.freeze(ErrorEnum);

export default ErrorEnum;